server:
  port: 2118
  maxConnections: 100
  idleTimeout: 60 # in seconds
core:
  cleanerInterval: 10 # in seconds
  namespace:
    shardCounts: # must be 2^n
      shmap: 8
      shhash: 8
      shcounter: 8
      shrbuffer: 8
      shset: 8
