services:
  memap:
    image: memap:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memap
    restart: unless-stopped
    ports:
      - "2118:2118"
    # volumes:
      # If you want to use your own config file, uncomment the line below
      # - ./config.yaml:/app/config.yaml:ro
